from django.urls import path

from .views import (
    admin_etablissement_availability,
    admin_etablissement_doctor_calendar,
    admin_etablissement_doctor_schedule,
    admin_etablissement_doctor_leaves,
    admin_etablissement_invitations,
    admin_etablissement_staff_create,
    admin_etablissement_staff_delete,
    admin_etablissement_staff_detail,
    admin_etablissement_staff_edit,
    admin_etablissement_staff_list,
    activate_account_view,
    dashboard,
    doctor_invitation_decision,
    doctor_invitations,
    forbidden_view,
    login_view,
    logout_view,
    setup_password_view,
    staff_attendance,
    staff_patient_create,
    staff_patient_receipt,
    super_admin_doctor_create,
    super_admin_doctor_delete,
    super_admin_doctor_detail,
    super_admin_doctor_edit,
    super_admin_doctor_list,
    super_admin_facility_create,
    super_admin_facility_delete,
    super_admin_facility_detail,
    super_admin_facility_edit,
    super_admin_facility_list,
    super_admin_user_create,
    super_admin_user_delete,
    super_admin_user_detail,
    super_admin_user_edit,
    super_admin_user_list,
)

urlpatterns = [
    path("activate-account/", activate_account_view, name="activate_account"),
    path("login/", login_view, name="login"),
    path("setup-password/", setup_password_view, name="setup_password"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", dashboard, name="dashboard"),
    path("admin-etablissement/invitations/", admin_etablissement_invitations, name="admin_etablissement_invitations"),
    path("admin-etablissement/disponibilites/", admin_etablissement_availability, name="admin_etablissement_availability"),
    path("admin-etablissement/disponibilites/<uuid:doctor_id>/calendrier/", admin_etablissement_doctor_calendar, name="admin_etablissement_doctor_calendar"),
    path("admin-etablissement/disponibilites/<uuid:doctor_id>/horaire/", admin_etablissement_doctor_schedule, name="admin_etablissement_doctor_schedule"),
    path("admin-etablissement/disponibilites/<uuid:doctor_id>/conges/", admin_etablissement_doctor_leaves, name="admin_etablissement_doctor_leaves"),
    path("admin-etablissement/staff/", admin_etablissement_staff_list, name="admin_etablissement_staff_list"),
    path("admin-etablissement/staff/create/", admin_etablissement_staff_create, name="admin_etablissement_staff_create"),
    path("admin-etablissement/staff/<uuid:user_id>/", admin_etablissement_staff_detail, name="admin_etablissement_staff_detail"),
    path("admin-etablissement/staff/<uuid:user_id>/edit/", admin_etablissement_staff_edit, name="admin_etablissement_staff_edit"),
    path("admin-etablissement/staff/<uuid:user_id>/delete/", admin_etablissement_staff_delete, name="admin_etablissement_staff_delete"),
    path("staff/attendance/", staff_attendance, name="staff_attendance"),
    path("staff/patients/create/", staff_patient_create, name="staff_patient_create"),
    path("staff/patients/<uuid:patient_id>/receipt/", staff_patient_receipt, name="staff_patient_receipt"),
    path("doctor/invitations/", doctor_invitations, name="doctor_invitations"),
    path("doctor/invitations/<uuid:invitation_id>/decision/", doctor_invitation_decision, name="doctor_invitation_decision"),
    path("super-admin/doctors/", super_admin_doctor_list, name="super_admin_doctor_list"),
    path("super-admin/doctors/create/", super_admin_doctor_create, name="super_admin_doctor_create"),
    path("super-admin/doctors/<uuid:doctor_id>/", super_admin_doctor_detail, name="super_admin_doctor_detail"),
    path("super-admin/doctors/<uuid:doctor_id>/edit/", super_admin_doctor_edit, name="super_admin_doctor_edit"),
    path("super-admin/doctors/<uuid:doctor_id>/delete/", super_admin_doctor_delete, name="super_admin_doctor_delete"),
    path("super-admin/facilities/", super_admin_facility_list, name="super_admin_facility_list"),
    path("super-admin/facilities/create/", super_admin_facility_create, name="super_admin_facility_create"),
    path("super-admin/facilities/<uuid:facility_id>/", super_admin_facility_detail, name="super_admin_facility_detail"),
    path("super-admin/facilities/<uuid:facility_id>/edit/", super_admin_facility_edit, name="super_admin_facility_edit"),
    path("super-admin/facilities/<uuid:facility_id>/delete/", super_admin_facility_delete, name="super_admin_facility_delete"),
    path("super-admin/users/", super_admin_user_list, name="super_admin_user_list"),
    path("super-admin/users/create/", super_admin_user_create, name="super_admin_user_create"),
    path("super-admin/users/<uuid:user_id>/", super_admin_user_detail, name="super_admin_user_detail"),
    path("super-admin/users/<uuid:user_id>/edit/", super_admin_user_edit, name="super_admin_user_edit"),
    path("super-admin/users/<uuid:user_id>/delete/", super_admin_user_delete, name="super_admin_user_delete"),
    path("forbidden/", forbidden_view, name="forbidden"),
]
