from django.urls import path

from .views import (
    dashboard,
    forbidden_view,
    login_view,
    logout_view,
    super_admin_doctor_create,
    super_admin_doctor_delete,
    super_admin_doctor_detail,
    super_admin_doctor_edit,
    super_admin_doctor_list,
    super_admin_facility_create,
    super_admin_facility_delete,
    super_admin_facility_detail,
    super_admin_facility_edit,
    super_admin_facility_list,
    super_admin_user_create,
    super_admin_user_delete,
    super_admin_user_detail,
    super_admin_user_edit,
    super_admin_user_list,
)

urlpatterns = [
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", dashboard, name="dashboard"),
    path("super-admin/doctors/", super_admin_doctor_list, name="super_admin_doctor_list"),
    path("super-admin/doctors/create/", super_admin_doctor_create, name="super_admin_doctor_create"),
    path("super-admin/doctors/<uuid:doctor_id>/", super_admin_doctor_detail, name="super_admin_doctor_detail"),
    path("super-admin/doctors/<uuid:doctor_id>/edit/", super_admin_doctor_edit, name="super_admin_doctor_edit"),
    path("super-admin/doctors/<uuid:doctor_id>/delete/", super_admin_doctor_delete, name="super_admin_doctor_delete"),
    path("super-admin/facilities/", super_admin_facility_list, name="super_admin_facility_list"),
    path("super-admin/facilities/create/", super_admin_facility_create, name="super_admin_facility_create"),
    path("super-admin/facilities/<uuid:facility_id>/", super_admin_facility_detail, name="super_admin_facility_detail"),
    path("super-admin/facilities/<uuid:facility_id>/edit/", super_admin_facility_edit, name="super_admin_facility_edit"),
    path("super-admin/facilities/<uuid:facility_id>/delete/", super_admin_facility_delete, name="super_admin_facility_delete"),
    path("super-admin/users/", super_admin_user_list, name="super_admin_user_list"),
    path("super-admin/users/create/", super_admin_user_create, name="super_admin_user_create"),
    path("super-admin/users/<uuid:user_id>/", super_admin_user_detail, name="super_admin_user_detail"),
    path("super-admin/users/<uuid:user_id>/edit/", super_admin_user_edit, name="super_admin_user_edit"),
    path("super-admin/users/<uuid:user_id>/delete/", super_admin_user_delete, name="super_admin_user_delete"),
    path("forbidden/", forbidden_view, name="forbidden"),
]
