from django.urls import path

from .views import (
    admin_etablissement_attendance,
    admin_etablissement_appointment_list,
    admin_etablissement_availability,
    admin_etablissement_detail,
    admin_etablissement_doctor_calendar,
    admin_etablissement_doctor_schedule,
    admin_etablissement_doctor_toggle_access,
    admin_etablissement_doctor_leaves,
    admin_etablissement_invitations,
    admin_etablissement_invitation_cancel,
    admin_etablissement_patient_list,
    admin_etablissement_staff_create,
    admin_etablissement_staff_delete,
    admin_etablissement_staff_detail,
    admin_etablissement_staff_edit,
    admin_etablissement_staff_list,
    abandon_exam_session,
    activate_patient_exam_session,
    activate_account_view,
    dashboard,
    exam_session_status_api,
    doctor_appointment_detail,
    doctor_appointments,
    doctor_availability,
    doctor_calendar,
    doctor_invitation_decision,
    doctor_invitation_open,
    doctor_invitations,
    doctor_leaves,
    doctor_patient_list,
    doctor_schedule,
    forbidden_view,
    health_professional_session_detail,
    health_professional_session_history,
    health_professional_session_lookup,
    login_view,
    logout_view,
    setup_password_view,
    staff_attendance,
    staff_appointments,
    staff_patient_detail,
    staff_patient_list,
    staff_patient_create,
    staff_patient_receipt,
    super_admin_doctor_create,
    super_admin_doctor_delete,
    super_admin_doctor_detail,
    super_admin_doctor_edit,
    super_admin_doctor_link_account,
    super_admin_doctor_list,
    super_admin_doctor_reset_password,
    super_admin_facility_create,
    super_admin_facility_delete,
    super_admin_facility_detail,
    super_admin_facility_edit,
    super_admin_facility_list,
    super_admin_role_create,
    super_admin_role_delete,
    super_admin_role_edit,
    super_admin_role_list,
    super_admin_user_create,
    super_admin_user_delete,
    super_admin_user_detail,
    super_admin_user_edit,
    super_admin_user_list,
    super_admin_user_reset_password,
)

urlpatterns = [
    path("activate-account/", activate_account_view, name="activate_account"),
    path("api/exam-sessions/activate/", activate_patient_exam_session, name="activate_patient_exam_session"),
    path("api/exam-sessions/<str:session_pin>/status/", exam_session_status_api, name="exam_session_status_api"),
    path("api/exam-sessions/<str:session_pin>/abandon/", abandon_exam_session, name="abandon_exam_session"),
    path("health-professional/session/", health_professional_session_lookup, name="health_professional_session_lookup"),
    path("health-professional/session/<str:session_pin>/", health_professional_session_detail, name="health_professional_session_detail"),
    path("health-professional/session/<str:session_pin>/history/", health_professional_session_history, name="health_professional_session_history"),
    path("login/", login_view, name="login"),
    path("setup-password/", setup_password_view, name="setup_password"),
    path("logout/", logout_view, name="logout"),
    path("dashboard/", dashboard, name="dashboard"),
    path("admin-etablissement/detail/", admin_etablissement_detail, name="admin_etablissement_detail"),
    path("admin-etablissement/invitations/", admin_etablissement_invitations, name="admin_etablissement_invitations"),
    path("admin-etablissement/invitations/<uuid:invitation_id>/cancel/", admin_etablissement_invitation_cancel, name="admin_etablissement_invitation_cancel"),
    path("admin-etablissement/attendance/", admin_etablissement_attendance, name="admin_etablissement_attendance"),
    path("admin-etablissement/patients/", admin_etablissement_patient_list, name="admin_etablissement_patient_list"),
    path("admin-etablissement/appointments/", admin_etablissement_appointment_list, name="admin_etablissement_appointment_list"),
    path("admin-etablissement/disponibilites/", admin_etablissement_availability, name="admin_etablissement_availability"),
    path("admin-etablissement/disponibilites/<uuid:doctor_id>/calendrier/", admin_etablissement_doctor_calendar, name="admin_etablissement_doctor_calendar"),
    path("admin-etablissement/disponibilites/<uuid:doctor_id>/horaire/", admin_etablissement_doctor_schedule, name="admin_etablissement_doctor_schedule"),
    path("admin-etablissement/disponibilites/<uuid:doctor_id>/conges/", admin_etablissement_doctor_leaves, name="admin_etablissement_doctor_leaves"),
    path("admin-etablissement/disponibilites/<uuid:doctor_id>/toggle-access/", admin_etablissement_doctor_toggle_access, name="admin_etablissement_doctor_toggle_access"),
    path("admin-etablissement/staff/", admin_etablissement_staff_list, name="admin_etablissement_staff_list"),
    path("admin-etablissement/staff/create/", admin_etablissement_staff_create, name="admin_etablissement_staff_create"),
    path("admin-etablissement/staff/<uuid:user_id>/", admin_etablissement_staff_detail, name="admin_etablissement_staff_detail"),
    path("admin-etablissement/staff/<uuid:user_id>/edit/", admin_etablissement_staff_edit, name="admin_etablissement_staff_edit"),
    path("admin-etablissement/staff/<uuid:user_id>/delete/", admin_etablissement_staff_delete, name="admin_etablissement_staff_delete"),
    path("staff/attendance/", staff_attendance, name="staff_attendance"),
    path("staff/appointments/", staff_appointments, name="staff_appointments"),
    path("staff/patients/", staff_patient_list, name="staff_patient_list"),
    path("staff/patients/<uuid:patient_id>/", staff_patient_detail, name="staff_patient_detail"),
    path("staff/patients/create/", staff_patient_create, name="staff_patient_create"),
    path("staff/patients/<uuid:patient_id>/receipt/", staff_patient_receipt, name="staff_patient_receipt"),
    path("doctor/invitations/", doctor_invitations, name="doctor_invitations"),
    path("doctor/invitations/open/<str:token>/", doctor_invitation_open, name="doctor_invitation_open"),
    path("doctor/invitations/<uuid:invitation_id>/decision/", doctor_invitation_decision, name="doctor_invitation_decision"),
    path("doctor/availability/", doctor_availability, name="doctor_availability"),
    path("doctor/availability/schedule/", doctor_schedule, name="doctor_schedule"),
    path("doctor/availability/calendar/", doctor_calendar, name="doctor_calendar"),
    path("doctor/availability/leaves/", doctor_leaves, name="doctor_leaves"),
    path("doctor/appointments/", doctor_appointments, name="doctor_appointments"),
    path("doctor/appointments/<uuid:appointment_id>/", doctor_appointment_detail, name="doctor_appointment_detail"),
    path("doctor/patients/", doctor_patient_list, name="doctor_patient_list"),
    path("super-admin/doctors/", super_admin_doctor_list, name="super_admin_doctor_list"),
    path("super-admin/doctors/create/", super_admin_doctor_create, name="super_admin_doctor_create"),
    path("super-admin/doctors/<uuid:doctor_id>/", super_admin_doctor_detail, name="super_admin_doctor_detail"),
    path("super-admin/doctors/<uuid:doctor_id>/edit/", super_admin_doctor_edit, name="super_admin_doctor_edit"),
    path("super-admin/doctors/<uuid:doctor_id>/link-account/", super_admin_doctor_link_account, name="super_admin_doctor_link_account"),
    path("super-admin/doctors/<uuid:doctor_id>/reset-password/", super_admin_doctor_reset_password, name="super_admin_doctor_reset_password"),
    path("super-admin/doctors/<uuid:doctor_id>/delete/", super_admin_doctor_delete, name="super_admin_doctor_delete"),
    path("super-admin/facilities/", super_admin_facility_list, name="super_admin_facility_list"),
    path("super-admin/facilities/create/", super_admin_facility_create, name="super_admin_facility_create"),
    path("super-admin/facilities/<uuid:facility_id>/", super_admin_facility_detail, name="super_admin_facility_detail"),
    path("super-admin/facilities/<uuid:facility_id>/edit/", super_admin_facility_edit, name="super_admin_facility_edit"),
    path("super-admin/facilities/<uuid:facility_id>/delete/", super_admin_facility_delete, name="super_admin_facility_delete"),
    path("super-admin/roles/", super_admin_role_list, name="super_admin_role_list"),
    path("super-admin/roles/create/", super_admin_role_create, name="super_admin_role_create"),
    path("super-admin/roles/<uuid:role_id>/edit/", super_admin_role_edit, name="super_admin_role_edit"),
    path("super-admin/roles/<uuid:role_id>/delete/", super_admin_role_delete, name="super_admin_role_delete"),
    path("super-admin/users/", super_admin_user_list, name="super_admin_user_list"),
    path("super-admin/users/create/", super_admin_user_create, name="super_admin_user_create"),
    path("super-admin/users/<uuid:user_id>/", super_admin_user_detail, name="super_admin_user_detail"),
    path("super-admin/users/<uuid:user_id>/edit/", super_admin_user_edit, name="super_admin_user_edit"),
    path("super-admin/users/<uuid:user_id>/reset-password/", super_admin_user_reset_password, name="super_admin_user_reset_password"),
    path("super-admin/users/<uuid:user_id>/delete/", super_admin_user_delete, name="super_admin_user_delete"),
    path("forbidden/", forbidden_view, name="forbidden"),
]
